### PR TITLE
move formplayer onto machines with free mem

### PR DESCRIPTION
**Pull request by dannyroberts**
formplayer0 => proxy0
formplayer1 => kafka0

My plan is to ansible deploy just formplayer to the new machines (without making proxy changes) and then to rsync the respective data directories. (Hopefully the proxy preserves hashing order like I think it does.) Then I'll deploy the proxy to smoothly switch over to the new machines, and then we can merge this

### CODE REVIEW

**Comment by gcapalbo** [comment]
do we have a sense for how running formplayer will affect the other services running on those machines during peak times?

if not, would it be better to just add an additional instance of formplayer on those machines instead of moving them, so that we have 4 total instead of just these 2?

**Comment by dannyroberts** [comment]
I think we don't want to leave formplayer on the current machines because nearly all the memory is taken up by riak (it's not a matter of formplayer being over worked—it simply can't get the full amount of physical RAM it's asking for).

I'm not too concerned about proxy0 and kafka0; they're both massively oversized (e.g 50+GB RAM free each), at least in terms of memory, and formplayer seems to have a pretty low footprint resource-wise.

Does that help @gcapalbo, or do you think there's reason for concern?

**Review by gcapalbo — APPROVED** [review]
ok, sounds ok

**Review by mkangia — APPROVED** [review]
I am sure you have it in your steps, but just flagging that Its important to do a QA once that change is made to ensure things are working well.
@javierwilson added something to nginx for formplayer to work correctly, do we need to add anything for new machines then?

Good luck!

**Comment by dannyroberts** [comment]
The switch-over is all complete and everything seems to be workings smoothly. I copied over all the sqlite dbs as well, so this shouldn't even result in more syncs or anything (though that probably would have been fine).

**Pull request merged**
