### PR TITLE
Delay kill

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts @gcapalbo 

if at first you don't succeed, try again in 3 minutes

### CODE REVIEW

**Comment by benrudolph** [comment]
hold on! gonna make an adjustment

**Comment by benrudolph** [comment]
ok 👍 this'll run it after restart...

**Review by dannyroberts — APPROVED** [review]
I heartily approve

**Comment by benrudolph** [comment]
@gcapalbo i know you were interested in consolidating the two shutdown methods. i think i'm going to go with this to start so i can stop having to babysit every deploy and if it works i'll make a `kill_celery_worker_by_hostname` command that takes a hostname arg and we can call that management command from supervisor. i have to do some testing to make sure it goes into warm shutdown. the docs just say "graceful shutdown" which i assume is a warm shutdown: http://docs.celeryproject.org/en/latest/userguide/workers.html#remote-shutdown. but will test

**Comment by gcapalbo** [comment]
hmm, i feel like this keeps getting more complicated. i hope this is just a temporary solution and not a permanent one.  my vote would still be to find the way that shuts down the workers reliably and exclusively use that as our method.

**Comment by benrudolph** [comment]
agreed, i'm unfortunately in a funny state where i don't think it makes sense to rollback, but we can't keep having these pingdom down messages and getting to the bottom of it has proven difficult. it's pretty much, try this solution and hope it works since we can't reliably reproduce. definitely not going to stop trying to get it to work properly though

also the other fix where we called this originally got reverted, so this is the only time we call `kill_stale`

**Pull request merged**
