### PR TITLE
GEvent for background queue

### PR DESCRIPTION
**Pull request by benrudolph**
@gcapalbo going to put this up on staging

### CODE REVIEW

**Review by gcapalbo — APPROVED** [review]
sounds good, i think one thing to be aware of is that i had tried boosting the concurrency only to 8 through flower on friday and we got a lot of es errors when i did that. might be less of an issue now though since there should be less contention with rabbit not being hosted there

**Comment by gcapalbo** [comment]
@benrudolph i merged master to resolve conflicts with staging, and also removed the max tasks per child setting since it doesn't apply with gevent

i'm also starting to think concurrency 20 might be too much with the other issues we've been having

**Comment by benrudolph** [comment]
thanks this kind of fell to the backlog. agree that the high concurrency is probably not the wisest thing to do given the recent issues

**Comment by nickpell** [comment]
conflicting with master - is it safe to remove this branch from staging.yaml?

**Comment by benrudolph** [comment]
Yea sorry

**Pull request closed without merging**
