### PR TITLE
refactor operations 2

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts one more of these guys, and i'll be happy. best read 🐟 . resumable deploys is on my list for PIDs and i really really needed to organize this a bit. 1400 line fabfile down to 645 lines. ran a staging deploy successfully. gonna test out a few more things, but should be ready for review.

cc: @proteusvacuum

### CODE REVIEW

**Comment by benrudolph** [comment]
ok i think this and his friend https://github.com/dimagi/commcare-hq-deploy/pull/62 are ready. https://github.com/dimagi/commcare-hq-deploy/pull/62 should probably be merged first

**Comment by proteusvacuum** [comment]
:+1: will let @dannyroberts merge

**Comment by dannyroberts** [comment]
Looks good!

**Comment by benrudolph** [comment]
@dimagi/team-commcare-hq as briefly mentioned in the sync today, this PR will allow for two new features:

`fab <env> setup_release:keep_days=10` - this will create a private release that will be ignored by the deploy reaper until that time has passed. 10 days is from the time of running the command

`fab <env> deploy:resume=yes` - this will resume a failed deployed from where you left off!

**Comment by NoahCarnahan** [comment]
Resuming will be sweet! 🍬 🍰 🍨 🍭 🍹

**Pull request merged**
