### PR TITLE
Run git gc in the background.

### PR DESCRIPTION
**Pull request by emord**
@dannyroberts @nickpell

### CODE REVIEW

**Comment by emord** [comment]
hmm. this doesn't work for some reason...

**Comment by benrudolph** [comment]
in other situations where we wanted to do this, we used the `at` command: https://github.com/dimagi/commcare-hq-deploy/blob/master/fab/operations/db.py#L19

**Comment by emord** [comment]
@benrudolph I think that that is still synchronous right? I was hoping to run `git gc` totally in the background so that it returns immediately and goes on to restarting services

**Comment by emord** [comment]
Was using this incorrectly before. fixed

**Review by benrudolph — APPROVED** [review]

**Pull request merged**
