### PR TITLE
postgres replication vars

### PR DESCRIPTION
**Pull request by snopoke**
Goes with https://github.com/dimagi/commcarehq-ansible/pull/962

buddy @nickpell

### CODE REVIEW

**Review by nickpell — APPROVED** [review]

**Review by calellowitz — APPROVED** [review]
changes look good but there is a lot of commented out work. is that on purpose

**Comment by snopoke** [comment]
The commented out bit are for hqstandby1 which doesn't exist yet

**Comment by snopoke** [comment]
This is now deployed for ICDS

**Comment by snopoke** [comment]
Still to be deployed to prod and softlayer but I think safer to have it merged.

**Pull request merged**
