### PR TITLE
disable some queues

### PR DESCRIPTION
**Pull request by snopoke**
@calellowitz @sravfeyn 

Disable these until the GZB users have been deleted to prevent sending out SMS's etc.

### CODE REVIEW

**Comment by gcapalbo** [comment]
@snopoke i don't have much context here but fyi the tasks will still keep queuing up and then will be processed all at once when these workers come back online (not sure if that's intended or not)

**Comment by calellowitz** [comment]
That does not sound good. we could always purge the queues before them back online. Would that work @gcapalbo ?

**Comment by snopoke** [comment]
Hey, that's not intended. Basically what's going to happen is that the user
data for all users (except test users) is going to be deleted at some later
point in time.

In the mean time we need to be able to do QA on the domain without firing
reminders etc.

What approach would you suggest?

**Comment by gcapalbo** [comment]
@snopoke @calellowitz there should only be one domain right? i don't have access so i can't check but i think all the reminders only send emails for the issue tracker at this point and don't send any sms. if you want those to stop, probably the easiest way to do so would be to just deactivate those reminders (can do so from the Messaging -> Reminders page).

for repeaters, i'm not sure how to stop that without deleting the forwarding rules (or introducing a one-off feature flag) but based on the domain on the india server it doesn't look like there are any forwarding rules configured.

also, let me know when/how you're going to be doing the deleting and i can let you know what messaging models (if any) need to be deleted as well.

**Comment by gcapalbo** [comment]
@snopoke @calellowitz if you agree with my comments above, can we revert this?

@sravfeyn - we won't be able to test the gateway setup if this change gets deployed

**Pull request merged**
