### PR TITLE
Update release.py

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts, wow somehow never noticed this...

### CODE REVIEW

**Comment by benrudolph** [comment]
this is wrong (will come back to it later)

**Comment by benrudolph** [comment]
i believe the only one broken is the static cache one not the other dirs

**Comment by dannyroberts** [comment]
Yeah, the problem is creating the `js` and then moving the other `js` into it. The same line if the `js` dir doesn't exist means "copy the original dir to the new location" (which is what you want) instead of copy it _into_ the existing directory. In other other examples, I think `bower_components` doesn't yet exist when you `cp` the old one, so the previous command worked as intended.

**Comment by benrudolph** [comment]
exactly. since this is an uncreated nested dir, removing the `mkdir` won't
work, but removing the last `js` will. thanks for catching 😀

**Pull request merged**
