### PR TITLE
reenabling periodic queues

### PR DESCRIPTION
**Pull request by calellowitz**
@snopoke @emord @javierwilson @sravfeyn @dannyroberts 
This enables periodic queues on the new icds cluster. It will require a fab deploy before it takes effect

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Should we hold of on deploying this (at least SMS) until SMS is working?

**Comment by calellowitz** [comment]
that makes sense to me. I had not read the doc carefully enough and didnt see the line mentioning this so figured i would go ahead and make the PR. Now that its here we can wait to deploy until ready

**Comment by czue** [comment]
(stuck a don't merge label on just for clarity)

**Comment by dannyroberts** [comment]
When you merge this, remember to also merge into commcarehq-ansible as per https://github.com/dimagi/commcare-hq/pull/18959#issuecomment-353356358

**Comment by dannyroberts** [comment]
(Also, I made this branch https://github.com/dimagi/commcarehq-ansible/compare/ce/icds-periodic?expand=1 in case you want to just PR and merge that instead of merging this and manually merging into commcarehq-ansible)

**Comment by dannyroberts** [comment]
Going with https://github.com/dimagi/commcarehq-ansible/pull/1193 and later followup instead.

**Pull request closed without merging**
