### PR TITLE
new celery machine for softlayer

### PR DESCRIPTION
**Pull request by javierwilson**

### CODE REVIEW

**Comment by gcapalbo** [comment]
@javierwilson we'll also need to specify in the environments file which worker goes where: https://github.com/dimagi/commcare-hq-deploy/blob/e3baf9c981d6d5498d62ae1ea5f306a45daa2a9c/fab/environments.yml#L25

we can split them up like we did for prod. only prod has one extra machine (hqcelery2), so for the prod ones that we put on hqcelery2, we can just split them up for softlayer on the two machines we have, putting the main worker on one, and the saved exports and background on the other.

**Comment by javierwilson** [comment]
@benrudolph @snopoke any thoughts?

**Comment by snopoke** [comment]
```
celery_processes:
    '10.162.36.233':  # celery0
      periodic:
        server_whitelist: '10.162.36.233'
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 200
      ucr_queue:
        concurrency: 4
      ucr_indicator_queue:
        concurrency: 1
      main:
        concurrency: 8
      saved_exports_queue:
        concurrency: 3
    '10.162.36.194':  # celery1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 8
      logistics_reminder_queue:
        concurrency: 2
      logistics_background_queue:
        concurrency: 2
      async_restore_queue:
        concurrency: 4
      background_queue:
        concurrency: 4
      flower: {}
```

**Comment by javierwilson** [comment]
@snopoke @gcapalbo added the queue distribution to enviroments...

**Review by snopoke — APPROVED** [review]

**Comment by emord** [comment]
i'll deploy this today

**Comment by gcapalbo** [comment]
i had to shift all workers back to celery0 tonight: https://github.com/dimagi/commcare-hq-deploy/pull/272

celery1 couldn't connect to couch. might be a whitelisting issue - i sent an email to get the public ip added for celery1

**Comment by javierwilson** [comment]
Do they need to connect using a public IP? I don't think we are actually using public IP for celery1

**Comment by javierwilson** [comment]
ok, couch is external, got it now.

**Comment by gcapalbo** [comment]
(issue resolved, and i just put the workers back on celery1: https://github.com/dimagi/commcare-hq-deploy/pull/273)

**Comment by benrudolph** [comment]
can we bump async queue to 8 instead of 4? @javierwilson https://github.com/dimagi/commcare-hq-deploy/pull/274

**Pull request merged**
