### PR TITLE
Use different method for shutdown

### PR DESCRIPTION
**Pull request by benrudolph**
@gcapalbo Going to do some testing on staging, so don't merge yet, but hopefully this'll be a more sustainable solution

cc: @NoahCarnahan

### CODE REVIEW

**Comment by benrudolph** [comment]
we may want to handle the exit code 1 and do a retry or something

**Comment by czue** [comment]
haha such a battle. :popcorn:

**Comment by gcapalbo** [comment]
@benrudolph yeah i was going to suggest retrying on exit code 1 as you said. otherwise, looks good to me

**Comment by benrudolph** [comment]
one thing we may be worried about is the memory overhead it now takes to shut down a celery worker. running a management command takes 100MB - 160MB of ram. If we have 5 of these it means we take ~0.5GB to shut down the workers. don't think it's a blocker but something to be aware of

**Comment by benrudolph** [comment]
Ok this is deployed to staging and works on restart. g2m from my perspective.  let's see it works! 🔬

**Comment by gcapalbo** [comment]
do you think it's worth trying to catch exit code 1 before we release? one upside to doing that is it will make us more proactive when it doesn't work

**Comment by benrudolph** [comment]
sure, were you thinking something like `if (exit_code == 1) redo the same command`? guessing we don't want to make it too complex or give it the potential to become an infinite loop

**Comment by gcapalbo** [comment]
yeah, though now that i think about it maybe it's better to try this out first and see how it goes. better to not make it too complicated unless we need to.

let me know what you think - i'm good to merge and try it out if you are

**Comment by benrudolph** [comment]
ok sounds good to me. staging has undergone a few restarts and two deploys with no weird things showing up, merging

**Pull request merged**
