### PR TITLE
further split ICDS static UCR pillows

### PR DESCRIPTION
**Pull request by snopoke**
@emord @benrudolph

### CODE REVIEW

**Comment by emord** [comment]
@snopoke can you add these to default.yml?

I think you also need to add these in settings.py on HQ

**Comment by snopoke** [comment]
I don't think they need to be in `default.yml` since they're only going to get added to ICDS localsettings.

Also they shouldn't be in `settings.py` since they're only for ICDS - unless you're saying I should just add them there rather than into ICDS localsettings.

**Comment by emord** [comment]
Ah. ok. I didn' realize you're only adding it to the localsettings.

**Review by emord — APPROVED** [review]

**Comment by benrudolph** [comment]
very cool

**Pull request merged**
