### PR TITLE
Add hqdb1 to prod inventory

### PR DESCRIPTION
**Pull request by kaapstorm**
@snopoke, does this look right? 

(I can confirm secondary storage is /dev/xvdb)

### CODE REVIEW

**Comment by kaapstorm** [comment]
@javierwilson, Simon has a lot on his plate right now. Do you know whether I need to give more config for the new DB machine, or will the defaults be OK? -- I noticed the ICDS DB machines have a lot of vars set, and each of them has a hot standby.

**Review by snopoke — APPROVED** [review]
looks good. I don't think you need any of the other vars.

**Comment by kaapstorm** [comment]
"set datadog_integration_cloudant=true for db0 on india" -- do you mean "on prod", @snopoke ?

**Review by javierwilson — APPROVED** [review]

**Comment by javierwilson** [comment]
no standby for hqdb1?

**Comment by snopoke** [comment]
@kaapstorm no I mean on India since I removed that var from the `postgresql` group it needs to be set on the host in the inventory

**Pull request merged**
